/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VacationRequestService } from "../vacationRequest.service";
import { VacationRequestCreateInput } from "./VacationRequestCreateInput";
import { VacationRequest } from "./VacationRequest";
import { VacationRequestFindManyArgs } from "./VacationRequestFindManyArgs";
import { VacationRequestWhereUniqueInput } from "./VacationRequestWhereUniqueInput";
import { VacationRequestUpdateInput } from "./VacationRequestUpdateInput";
import { ApprovalFindManyArgs } from "../../approval/base/ApprovalFindManyArgs";
import { Approval } from "../../approval/base/Approval";
import { ApprovalWhereUniqueInput } from "../../approval/base/ApprovalWhereUniqueInput";
import { VacationRequestDto } from "../VacationRequestDto";

export class VacationRequestControllerBase {
  constructor(protected readonly service: VacationRequestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VacationRequest })
  async createVacationRequest(
    @common.Body() data: VacationRequestCreateInput
  ): Promise<VacationRequest> {
    return await this.service.createVacationRequest({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        startDate: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [VacationRequest] })
  @ApiNestedQuery(VacationRequestFindManyArgs)
  async vacationRequests(
    @common.Req() request: Request
  ): Promise<VacationRequest[]> {
    const args = plainToClass(VacationRequestFindManyArgs, request.query);
    return this.service.vacationRequests({
      ...args,
      select: {
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        startDate: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VacationRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async vacationRequest(
    @common.Param() params: VacationRequestWhereUniqueInput
  ): Promise<VacationRequest | null> {
    const result = await this.service.vacationRequest({
      where: params,
      select: {
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        endDate: true,
        id: true,
        startDate: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VacationRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVacationRequest(
    @common.Param() params: VacationRequestWhereUniqueInput,
    @common.Body() data: VacationRequestUpdateInput
  ): Promise<VacationRequest | null> {
    try {
      return await this.service.updateVacationRequest({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          endDate: true,
          id: true,
          startDate: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VacationRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVacationRequest(
    @common.Param() params: VacationRequestWhereUniqueInput
  ): Promise<VacationRequest | null> {
    try {
      return await this.service.deleteVacationRequest({
        where: params,
        select: {
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          endDate: true,
          id: true,
          startDate: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/approvals")
  @ApiNestedQuery(ApprovalFindManyArgs)
  async findApprovals(
    @common.Req() request: Request,
    @common.Param() params: VacationRequestWhereUniqueInput
  ): Promise<Approval[]> {
    const query = plainToClass(ApprovalFindManyArgs, request.query);
    const results = await this.service.findApprovals(params.id, {
      ...query,
      select: {
        approvalDate: true,
        approvedBy: true,
        createdAt: true,
        id: true,
        updatedAt: true,

        vacationRequest: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/approvals")
  async connectApprovals(
    @common.Param() params: VacationRequestWhereUniqueInput,
    @common.Body() body: ApprovalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvals: {
        connect: body,
      },
    };
    await this.service.updateVacationRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/approvals")
  async updateApprovals(
    @common.Param() params: VacationRequestWhereUniqueInput,
    @common.Body() body: ApprovalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvals: {
        set: body,
      },
    };
    await this.service.updateVacationRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/approvals")
  async disconnectApprovals(
    @common.Param() params: VacationRequestWhereUniqueInput,
    @common.Body() body: ApprovalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      approvals: {
        disconnect: body,
      },
    };
    await this.service.updateVacationRequest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/")
  @swagger.ApiOkResponse({
    type: VacationRequestDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async CreateVacationRequest(
    @common.Body()
    body: VacationRequestDto
  ): Promise<VacationRequestDto> {
    return this.service.CreateVacationRequest(body);
  }
}
